spring:
  datasource:
    url: jdbc:sqlite:identifier.sqlite
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # Always starts with empty database
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
